spring:
  application:
    name: cloud-commons
  profiles:
    active: office
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: provider-user # 路由规则id，自定义，唯一
          uri: lb://provider-user # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/items/**,/search/** # 这里是以请求路径作为判断规则

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
#      defaultZone: http://user:password123@127.0.0.1:8761/eureka
      defaultZone: http://user:password123@121.5.179.95:8761/eureka
#      defaultZone: http://user:password123@123.249.43.78:8761/eureka

zuul:
  routes:
    user-app:
      path: /user/**
      serviceId: provider-user
    sidecar-app:
      path: /sidecar/**
      serviceId: sidecar

feign:
  httpclient:
    enabled: true

whitelist:
  interfaceList:
    - /sys-dict/**
    - /sys-dict-data/**
    - /tab
    - /**

token:
  expires: 10

md5-key: isstech

message:
  Uid: messagemsm
  Key: 4244290725705277C83EE681D1F5E02F