server:
  port: 7910

spring:
  profiles: office
  redis:
    host: localhost
    port: 6379
    password: Da755734
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.5.179.95:3306/db1?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #    serviceTimezone=Asia/Shanghai
    username: root
    password: Da@755734
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 20MB
      # 设置总上传的文件大小
      max-request-size: 40MB
